# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name : Checkout
      uses: actions/checkout@v2.3.2
    - name: Setup JDK 
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle
      run: ./gradlew build
    - name: upload apk
      uses: actions/upload-artifact@v2.1.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
